### ISSUE TITLE
Buffer overflow on ground control arduino

### ISSUE THREAD

**Issue by JonBees** [JonBees/ArduinoFlightSoftware#31]

**Comment by LunarLionGNC** [comment]
The buffer fill-up issue is strongly correlated with the actuation of FO-U, FC-U, and AV5-M. Incidentally, on the LabView side, the buttons for these 3 actuators were all of the ones for which confirmation messages were made during this summer. These confirmation messages were made in a manner different from all of the others and it is highly likely that this is the source of the problem; it is probable that because of the way these confirmation messages work, they send their respective command character more frequently than the other confirmation messages and this is fed into the buffer.

-Vikas

**Comment by LunarLionGNC** [comment]
The buffer issue has been resolved in the following way but I think it should be tested with PUMA before officially resolving it (although the problem was on LabView so it shouldn't make a difference). The newer confirmation messages were re-done using the older format and, using the PUMA simulator setup, the buffer issue was shown to be resolved.

-Vikas
